changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
        - major
    - title: Features
      labels:
        - feat
        - feature
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
        - bugfix
    - title: Documentation
      labels:
        - docs
    - title: Maintenance
      labels:
        - chore
        - ci
        - refactor
  exclude:
    labels:
      - skip-changelog
